# -*- coding: utf-8 -*-
"""
Script sekali-pakai untuk mengisi katalog terjemahan (en identity,
id terjemahan asli) berdasarkan messages.pot hasil extract, plus
menambahkan entry untuk label menu dinamis (yang tersimpan sebagai
data di database, bukan string literal di template, sehingga tidak
ikut ter-extract otomatis oleh pybabel).
"""

import polib

POT_PATH = "messages.pot"
EN_PO_PATH = "app/translations/en/LC_MESSAGES/messages.po"
ID_PO_PATH = "app/translations/id/LC_MESSAGES/messages.po"

# Terjemahan Indonesia untuk string yang di-extract otomatis
# (sumbernya sudah berupa bahasa Inggris).
ID_TRANSLATIONS = {
    "The uploaded file is too large (maximum 5 MB).": "Ukuran file yang diunggah terlalu besar (maksimal 5 MB).",
    "You do not have access to this page.": "Anda tidak memiliki akses ke halaman ini.",
    "You do not have permission to perform this action.": "Anda tidak memiliki izin untuk melakukan tindakan ini.",
    "Logo format must be PNG, JPG, JPEG, WEBP, or SVG.": "Format logo harus PNG, JPG, JPEG, WEBP, atau SVG.",
    "Application name is required.": "Nama aplikasi wajib diisi.",
    "Application settings saved successfully.": "Pengaturan aplikasi berhasil disimpan.",
    "Incorrect username or password.": "Username atau password salah.",
    "You have been logged out.": "Anda telah logout.",
    "Category name is required.": "Nama kategori wajib diisi.",
    "Category already exists.": "Kategori sudah ada.",
    "Category added successfully.": "Kategori berhasil ditambahkan.",
    "Category updated successfully.": "Kategori berhasil diperbarui.",
    "Category deleted successfully.": "Kategori berhasil dihapus.",
    "Location name is required.": "Nama lokasi wajib diisi.",
    "Location already exists.": "Lokasi sudah ada.",
    "Location added successfully.": "Lokasi berhasil ditambahkan.",
    "Location updated successfully.": "Lokasi berhasil diperbarui.",
    "Location deleted successfully.": "Lokasi berhasil dihapus.",
    "Department name is required.": "Nama departemen wajib diisi.",
    "Department already exists.": "Departemen sudah ada.",
    "Department added successfully.": "Departemen berhasil ditambahkan.",
    "Department updated successfully.": "Departemen berhasil diperbarui.",
    "Department deleted successfully.": "Departemen berhasil dihapus.",
    "Vendor name is required.": "Nama vendor wajib diisi.",
    "Vendor already exists.": "Vendor sudah ada.",
    "Vendor added successfully.": "Vendor berhasil ditambahkan.",
    "Vendor updated successfully.": "Vendor berhasil diperbarui.",
    "Vendor deleted successfully.": "Vendor berhasil dihapus.",
    "Full name is required.": "Nama lengkap wajib diisi.",
    "New password confirmation does not match.": "Konfirmasi password baru tidak cocok.",
    "Password must be at least %(min_length)s characters.": "Password minimal %(min_length)s karakter.",
    "Profile updated successfully.": "Profil berhasil diperbarui.",
    "Toggle sidebar": "Buka/tutup sidebar",
    "Profile": "Profil",
    "Logout": "Keluar",
    "Main menu": "Menu utama",
    "Dashboard": "Dasbor",
    "Asset Tracker summary information": "Ringkasan informasi Asset Tracker",
    "Asset List": "Daftar Asset",
    "Movement Report": "Laporan Mutasi",
    "Total Assets": "Total Asset",
    "Total Asset Value": "Total Nilai Asset",
    "Status Types": "Jenis Status",
    "Movements (12 Months)": "Mutasi (12 Bulan)",
    "Assets by Status": "Asset Berdasarkan Status",
    "Status": "Status",
    "Count": "Jumlah",
    "No status data yet.": "Belum ada data status.",
    "Assets by Category": "Asset Berdasarkan Kategori",
    "Category": "Kategori",
    "No category data yet.": "Belum ada data kategori.",
    "Assets by Location": "Asset Berdasarkan Lokasi",
    "Location": "Lokasi",
    "No location data yet.": "Belum ada data lokasi.",
    "Assets by Department": "Asset Berdasarkan Departemen",
    "Department": "Departemen",
    "No department data yet.": "Belum ada data departemen.",
    "Asset Movements - Last 12 Months": "Mutasi Asset 12 Bulan Terakhir",
    "movements": "mutasi",
    "No movement data yet.": "Belum ada data mutasi.",
    "Total Movements": "Total Mutasi",
    "Entire movement history": "Seluruh histori mutasi",
    "Total Corrections": "Total Koreksi",
    "Entire movement correction history": "Seluruh histori koreksi mutasi",
    "Movements This Month": "Mutasi Bulan Ini",
    "Corrections This Month": "Koreksi Bulan Ini",
    "Corrections in the current month": "Koreksi pada bulan berjalan",
    "Recent Assets": "Asset Terbaru",
    "View All": "Lihat Semua",
    "No.": "No",
    "Asset Tag": "Kode Asset",
    "Asset Name": "Nama Asset",
    "Active": "Aktif",
    "Maintenance": "Perbaikan",
    "Lost": "Hilang",
    "Retired": "Non-aktif",
    "No assets yet.": "Belum ada asset.",
    "Recent Asset Movements": "Mutasi Asset Terbaru",
    "View Report": "Lihat Laporan",
    "Movement No.": "No. Mutasi",
    "Date": "Tanggal",
    "Asset": "Asset",
    "From": "Dari",
    "To": "Ke",
    "Username": "Username",
    "Password": "Password",
    "Login": "Masuk",
    "My Profile": "Profil Saya",
    "Inactive": "Nonaktif",
    "Joined": "Bergabung",
    "Edit Profile": "Edit Profil",
    "Username cannot be changed by yourself, contact the administrator.": "Username tidak bisa diubah sendiri, hubungi administrator.",
    "Full Name": "Nama Lengkap",
    "Leave blank if you do not want to change your password.": "Kosongkan bila tidak ingin mengganti password.",
    "New Password": "Password Baru",
    "Confirm New Password": "Konfirmasi Password Baru",
    "Save Changes": "Simpan Perubahan",
    "Add Category": "Tambah Kategori",
    "Category Name": "Nama Kategori",
    "Example: Laptop": "Contoh: Laptop",
    "Description": "Keterangan",
    "Category description...": "Keterangan kategori...",
    "Save": "Simpan",
    "Cancel": "Batal",
    "Edit Category": "Edit Kategori",
    "Categories": "Kategori",
    "Category Master": "Master Kategori",
    "Manage asset categories": "Kelola kategori asset",
    "Actions": "Aksi",
    "Edit": "Edit",
    "Delete this category?": "Hapus kategori ini?",
    "Delete": "Hapus",
    "No categories yet.": "Belum ada kategori.",
    "Add Department": "Tambah Departemen",
    "Department Name": "Nama Departemen",
    "Example: IT": "Contoh: IT",
    "Edit Department": "Edit Departemen",
    "Departments": "Departemen",
    "Department Master": "Master Departemen",
    "Manage asset user departments": "Kelola departemen pengguna asset",
    "Delete this department?": "Hapus departemen ini?",
    "No departments yet.": "Belum ada departemen.",
    "Add Location": "Tambah Lokasi",
    "Location Name": "Nama Lokasi",
    "Example: Office": "Contoh: Office",
    "Edit Location": "Edit Lokasi",
    "Locations": "Lokasi",
    "Location Master": "Master Lokasi",
    "Manage asset locations": "Kelola lokasi asset",
    "Delete this location?": "Hapus lokasi ini?",
    "No locations yet.": "Belum ada lokasi.",
    "Add Vendor": "Tambah Vendor",
    "Vendor Name": "Nama Vendor",
    "Company/vendor name": "Nama perusahaan/vendor",
    "Contact Person": "Kontak Person",
    "Phone": "Telepon",
    "Email": "Email",
    "Address": "Alamat",
    "Save Vendor": "Simpan Vendor",
    "Edit Vendor": "Edit Vendor",
    "Vendors": "Vendor",
    "Vendor Master": "Master Vendor",
    "Manage asset suppliers and vendors": "Kelola supplier dan vendor asset",
    "Vendor": "Vendor",
    "Delete this vendor?": "Hapus vendor ini?",
    "No vendors yet.": "Belum ada vendor.",
    "Application Settings": "Pengaturan Aplikasi",
    "Application name, logo, footer, and login page": "Nama aplikasi, logo, footer, dan halaman login",
    "Application Identity": "Identitas Aplikasi",
    "Application Name": "Nama Aplikasi",
    "Appears in the sidebar, browser tab, and login page.": "Muncul di sidebar, tab browser, dan halaman login.",
    "Footer Text": "Teks Footer",
    "Example: PT Tradecorp Indonesia © 2026": "Contoh: PT Tradecorp Indonesia © 2026",
    "Leave blank to use the default:": "Kosongkan untuk pakai default:",
    "Login Page Message": "Pesan di Halaman Login",
    "Example: Internal Asset Management System": "Contoh: Sistem Manajemen Asset Internal",
    "Save Settings": "Simpan Pengaturan",
    "Wide Logo (Sidebar)": "Logo Panjang (Sidebar)",
    "Wide logo": "Logo panjang",
    "No wide logo yet": "Belum ada logo panjang",
    "Remove wide logo (use default icon)": "Hapus logo panjang (pakai ikon default)",
    "Square Logo (Login & Favicon)": "Logo Kotak (Login & Favicon)",
    "Square logo": "Logo kotak",
    "No square logo yet": "Belum ada logo kotak",
    "Remove square logo (use default icon)": "Hapus logo kotak (pakai ikon default)",
    "Recommended: 1:1 (square) ratio, also used as the browser tab favicon.": "Disarankan: rasio 1:1 (persegi), dipakai juga sebagai favicon tab browser.",
    "Small text below the application name on the login page. May be left blank.": "Teks kecil di bawah nama aplikasi pada halaman login. Boleh dikosongkan.",
    "Recommended: wide (horizontal) shape, transparent background, height around 40-60px.": "Disarankan: bentuk melebar (horizontal), latar transparan, tinggi sekitar 40-60px.",
    "Toggle color scheme": "Ganti skema warna",
    "Light": "Terang",
    "Dark": "Gelap",
    "Auto": "Otomatis",
    "Sidebar Brand Display": "Tampilan Identitas Sidebar",
    "Choose how the app identity appears next to the sidebar menu.": "Pilih bagaimana identitas aplikasi ditampilkan di sebelah menu sidebar.",
    "Logo only": "Hanya Logo",
    "Application name only": "Hanya Nama Aplikasi",
    "Logo and application name": "Logo dan Nama Aplikasi",
    "If no wide logo has been uploaded yet, the sidebar falls back to the application name regardless of this setting.": "Jika logo lebar belum diunggah, sidebar akan otomatis menampilkan nama aplikasi terlepas dari pengaturan ini.",

    # --- login.html (split-panel redesign) ---
    "Welcome": "Selamat Datang",
    "Manage and track your company assets in one integrated system.": "Kelola dan pantau aset perusahaan Anda dalam satu sistem terintegrasi.",
    "Sign In": "Masuk ke Akun",
    "Enter your credentials to access your account.": "Masukkan kredensial Anda untuk mengakses akun.",
    "Show password": "Tampilkan password",
    "Remember me": "Ingat saya",
    "Forgot your password? Contact your administrator.": "Lupa password? Hubungi administrator Anda.",

    # --- index.html (dashboard / "Asset" sidebar page) ---
    "Dashboard Asset Management": "Dashboard Asset Management",
    "Company asset monitoring and management": "Monitoring dan pengelolaan aset perusahaan",
    "Active Assets": "Asset Active",
    "Status distribution of all assets": "Distribusi status seluruh asset",
    "Number of assets by category": "Jumlah asset berdasarkan category",
    "Asset distribution by location": "Distribusi asset berdasarkan lokasi",
    "Asset distribution by department": "Distribusi asset berdasarkan department",
    "Active Warranty": "Warranty Aktif",
    "Warranty Expiring Soon": "Warranty Akan Habis",
    "Maximum 30 days": "Maksimal 30 hari",
    "Warranty Expired": "Warranty Expired",
    "Unknown Warranty": "Warranty Tidak Diketahui",
    "Warranty Alert": "Warranty Alert",
    "Warranty priorities that need attention": "Prioritas warranty yang membutuhkan perhatian",
    "View Alert": "Lihat Alert",
    "Warranty Notification Center": "Pusat Notifikasi Warranty",
    "Notification": "Notifikasi",
    "Expiring in ≤ 7 Days": "Akan Habis ≤ 7 Hari",
    "Expiring in 8–30 Days": "Akan Habis 8–30 Hari",
    'Click "View Alert" to see the list of assets that need immediate action.': 'Klik "Lihat Alert" untuk melihat daftar asset yang harus segera ditindaklanjuti.',
    "All Warranties": "Semua Warranty",
    "Notification Center": "Pusat Notifikasi",
    "Warranty expiring within a maximum of 30 days": "Warranty yang akan berakhir dalam maksimal 30 hari",
    "View Warranty Alert Detail": "Lihat Warranty Alert Detail",
    "Warranty": "Warranty",
    "Expires": "Berakhir",
    "Remaining": "Sisa",
    "Today": "Hari ini",
    "days": "hari",
    "No warranty expiring within 30 days.": "Tidak ada warranty yang akan habis dalam 30 hari.",
    "Warranty that has already expired": "Warranty yang sudah berakhir",
    "Expired": "Expired",
    "No expired warranty.": "Tidak ada warranty expired.",
    "10 most recently added assets": "10 asset terakhir ditambahkan",
    "No Status": "Tidak Ada Status",
    "Asset Detail": "Detail Asset",
    "No Category": "Tanpa Kategori",
    "No Location": "Tanpa Lokasi",
    "No Department": "Tanpa Department",

    # --- asset/movement_report.html ---
    "Asset Movement Report": "Laporan Mutasi Asset",
    "Asset movement history by movement date.": "Riwayat perpindahan asset berdasarkan tanggal movement.",
    "Printed from the Asset Tracker system.": "Dicetak dari sistem Asset Tracker.",
    "Print": "Cetak",
    "Export Excel": "Ekspor Excel",
    "Filtered Results": "Hasil Filter",
    "Most Common Destination Location": "Lokasi Tujuan Terbanyak",
    "Most Common Destination Department": "Department Tujuan Terbanyak",
    "Report Filter": "Filter Laporan",
    "Start Date": "Tanggal Mulai",
    "End Date": "Tanggal Akhir",
    "Apply Filter": "Terapkan Filter",
    "Reset": "Reset",
    "Showing movements from": "Menampilkan movement dari",
    "to": "sampai",
    "Showing movements until": "Menampilkan movement sampai",
    "Showing all movements.": "Menampilkan seluruh movement.",
    "Asset Movement Data": "Data Mutasi Asset",
    "movements shown": "movement ditampilkan",
    "Period:": "Periode:",
    "From:": "Mulai:",
    "Until:": "Sampai:",
    "Entire period": "Seluruh periode",
    "PIC": "PIC",
    "Reason / Description": "Alasan / Keterangan",
    "View Movement Detail": "Lihat Detail Movement",
    "Detail": "Detail",
    "No movement data": "Tidak ada data movement",
    "No asset movement data found": "Tidak ditemukan data mutasi asset",
    "for the selected period.": "pada periode yang dipilih.",
    "in the database.": "pada database.",
    "Reset Filter": "Reset Filter",
    "Showing": "Menampilkan",
    "of": "dari",
    "total movements.": "total movement.",
    "No movements displayed.": "Tidak ada movement yang ditampilkan.",

    # --- asset/list.html ---
    "Manage and monitor all company assets": "Kelola dan monitor seluruh asset perusahaan",
    "Print QR / Label": "Cetak QR / Label",
    "Export": "Export",
    "Add Asset": "Tambah Asset",
    "Search": "Cari",
    "Asset tag, name, brand, serial...": "Asset tag, nama, brand, serial...",
    "All Statuses": "Semua Status",
    "All Categories": "Semua Category",
    "All Locations": "Semua Location",
    "All Departments": "Semua Department",
    "All Vendors": "Semua Vendor",
    "Photo": "Foto",
    "Brand": "Brand",
    "Model": "Model",
    "Serial Number": "Serial Number",
    "No photo yet": "Belum ada foto",
    "No assets found.": "Tidak ada asset ditemukan.",
    "Try changing your search term or filters.": "Coba ubah kata pencarian atau filter Anda.",
    "assets": "asset",
    "Search:": "Pencarian:",
    "Asset page navigation": "Navigasi halaman asset",
    "Previous": "Sebelumnya",
    "Next": "Berikutnya",

    # --- asset/detail.html ---
    "Back": "Kembali",
    "Edit Asset": "Edit Asset",
    "Asset Photo": "Foto Asset",
    "No asset photo yet": "Belum ada foto asset",
    "Asset QR Code": "QR Code Asset",
    "Asset Information": "Informasi Asset",
    "Purchase Date": "Tanggal Pembelian",
    "Purchase Price": "Harga Pembelian",
    "Asset Movement History": "Riwayat Movement Asset",
    "Asset movement history": "Histori perpindahan asset",
    "Add Movement": "Tambah Mutasi",
    "Reason": "Alasan",
    "Movement Detail": "Detail Movement",
    "Movement QR": "QR Movement",
    "No movement history yet": "Belum ada riwayat movement",
    "This asset does not have any movement history yet.": "Asset ini belum memiliki riwayat perpindahan.",
    "Add First Movement": "Tambah Mutasi Pertama",
    "QR Code": "QR Code",

    # --- full-app translation sweep (warranty, movement forms/detail,
    #     asset add/edit, labels, history/import, user/menu mgmt,
    #     roles/backup/company) ---
    'Warranty Alert Detail': 'Detail Warranty Alert',
    'Warranty status monitoring for all assets': 'Monitoring status warranty seluruh asset',
    'Warranty Management': 'Manajemen Warranty',
    'Alert': 'Alert',
    'Total Warranty': 'Total Warranty',
    'Incomplete': 'Tidak Lengkap',
    'Search Asset': 'Cari Asset',
    'Asset tag, name, brand, model, serial number, vendor...': 'Asset tag, nama, brand, model, serial number, vendor...',
    'Warranty Status': 'Status Warranty',
    'Filter': 'Filter',
    'Warranty List': 'Daftar Warranty',
    'Showing warranty expiring within ≤ 7 days.': 'Menampilkan warranty yang akan habis dalam ≤ 7 hari.',
    'Showing warranty expiring within 8–30 days.': 'Menampilkan warranty yang akan habis dalam 8–30 hari.',
    'Showing warranty that has already expired.': 'Menampilkan warranty yang sudah expired.',
    'Showing warranty that is still active.': 'Menampilkan warranty yang masih aktif.',
    'Showing warranty with incomplete data.': 'Menampilkan warranty dengan data yang belum lengkap.',
    'Showing all warranty data.': 'Menampilkan seluruh data warranty.',
    'found': 'ditemukan',
    'Tag': 'Tag',
    'Brand / Model': 'Brand / Model',
    'Days Left': 'Sisa Hari',
    'SN:': 'SN:',
    'days ago': 'hari lalu',
    '≤ 7 Days': '≤ 7 Hari',
    '8–30 Days': '8–30 Hari',
    'View Asset Detail': 'Lihat Detail Asset',
    'Edit Asset / Update Warranty': 'Edit Asset / Update Warranty',
    'Warranty History': 'Riwayat Warranty',
    'No warranty data': 'Tidak ada data warranty',
    'No assets found matching the selected filter.': 'Tidak ditemukan asset yang sesuai dengan filter yang dipilih.',
    'Monitoring the warranty period for all assets.': 'Monitoring masa warranty seluruh asset.',
    'Expiring': 'Akan Habis',
    'Incomplete Data': 'Data Tidak Lengkap',
    'Apply': 'Terapkan',
    'Expiring within 30 Days': 'Akan Habis ≤ 30 Hari',
    'Asset warranty change history': 'Riwayat perubahan warranty asset',
    'Asset Tag:': 'Kode Asset:',
    'Brand:': 'Brand:',
    'Model:': 'Model:',
    'Serial:': 'Serial:',
    'changes recorded': 'riwayat perubahan tercatat',
    'Current Warranty:': 'Warranty Saat Ini:',
    'Change Date': 'Tanggal Perubahan',
    'Old Warranty': 'Warranty Lama',
    'Old End Date': 'Berakhir Lama',
    'New Warranty': 'Warranty Baru',
    'New End Date': 'Berakhir Baru',
    'Notes': 'Catatan',
    'No warranty history yet': 'Belum ada riwayat warranty',
    "Changes to this asset's warranty will be recorded automatically here.": 'Perubahan warranty pada asset ini akan tercatat otomatis di sini.',
    'Warranty Notifications': 'Notifikasi Warranty',
    'Center for monitoring warranties that need attention': 'Pusat monitoring warranty yang membutuhkan perhatian',
    'Warranty Detail': 'Detail Warranty',
    'Asset tag, name, brand, model, serial, vendor, location...': 'Asset Tag, nama, brand, model, serial, vendor, lokasi...',
    'Notification Status': 'Status Notifikasi',
    'All Notifications': 'Semua Notifikasi',
    'Critical ≤ 7 Days': 'Kritis ≤ 7 Hari',
    'Warning 8–30 Days': 'Peringatan 8–30 Hari',
    'Total Alerts': 'Total Alert',
    'Warranty Expiring Immediately': 'Warranty Segera Habis',
    'Warranty remaining a maximum of 7 days': 'Warranty tersisa maksimal 7 hari',
    'Tag:': 'Tag:',
    'Expires today': 'Habis hari ini',
    '1 day left': '1 hari lagi',
    'days left': 'hari lagi',
    'Update Warranty': 'Update Warranty',
    'No critical warranties.': 'Tidak ada warranty yang kritis.',
    'Warranty remaining 8 to 30 days': 'Warranty tersisa 8 sampai 30 hari',
    'Vendor:': 'Vendor:',
    'No warranties in the warning period.': 'Tidak ada warranty dalam periode peringatan.',
    'Warranty that has passed its end date': 'Warranty yang sudah melewati tanggal berakhir',
    'Expires:': 'Berakhir:',
    'Last checked:': 'Pemeriksaan terakhir:',
    'QR code to access the movement document': 'QR Code untuk mengakses dokumen mutasi asset',
    'Scan the QR code using your smartphone camera to open the movement information.': 'Scan QR Code menggunakan kamera smartphone untuk membuka informasi mutasi asset.',
    'Movement Date': 'Tanggal Mutasi',
    'Transfer': 'Perpindahan',
    'Document URL': 'URL Dokumen',
    'View Movement Proof': 'Lihat Bukti Mutasi',
    'Verify': 'Verifikasi',
    'Print QR': 'Cetak QR',
    'Movement Correction History': 'Riwayat Koreksi Movement',
    'History of asset movement data changes': 'Riwayat perubahan data movement asset',
    'Correct Movement': 'Koreksi Movement',
    'Movement Information': 'Informasi Mutasi',
    'Correction History': 'Riwayat Koreksi',
    'Corrections': 'Koreksi',
    'Correction Time': 'Waktu Koreksi',
    'Data Before': 'Data Sebelum',
    'Data After': 'Data Sesudah',
    'Reason & Notes': 'Alasan & Catatan',
    'No correction reason.': 'Tidak ada alasan koreksi.',
    'No Correction History Yet': 'Belum Ada Riwayat Koreksi',
    'This movement has never been corrected.': 'Movement ini belum pernah dikoreksi.',
    'Create Correction': 'Buat Koreksi',
    'Asset Movement Verification': 'Verifikasi Mutasi Asset',
    'Asset Movement Verified': 'Mutasi Asset Terverifikasi',
    'Movement data found in the Asset Tracker system': 'Data mutasi ditemukan di sistem Asset Tracker',
    'VALID DATA': 'DATA VALID',
    'Location Change': 'Perpindahan Lokasi',
    'BEFORE': 'SEBELUM',
    'AFTER': 'SESUDAH',
    'Department Change': 'Perpindahan Department',
    'PIC Change': 'Perpindahan PIC',
    'Movement Reason': 'Alasan Mutasi',
    'Verification Information': 'Informasi Verifikasi',
    'The data above is taken directly from the asset movement record stored in the Asset Tracker system.': 'Data di atas diambil langsung dari catatan mutasi asset yang tersimpan pada sistem Asset Tracker.',
    'Use the movement number and Asset Tag as a reference if further verification is required.': 'Gunakan nomor mutasi dan Asset Tag sebagai referensi apabila diperlukan pemeriksaan lebih lanjut.',
    'View QR': 'Lihat QR',
    'Asset Movement Proof': 'Bukti Mutasi Asset',
    'Back to History': 'Kembali ke Riwayat',
    'Verification QR': 'QR Verifikasi',
    'Print A4': 'Cetak A4',
    'Movement Verification QR': 'QR Verifikasi Mutasi',
    'Scan to verify': 'Scan untuk verifikasi',
    'COMPANY NAME': 'NAMA PERUSAHAAN',
    'Logo': 'Logo',
    'Tel.': 'Telp.',
    'ASSET MOVEMENT PROOF': 'BUKTI MUTASI ASSET',
    'Document Information': 'Informasi Dokumen',
    'Created': 'Dibuat',
    'COMPLETED': 'SELESAI',
    'Asset Identity': 'Identitas Asset',
    'Asset Status': 'Status Asset',
    'Asset Transfer Detail': 'Detail Perpindahan Asset',
    'DESCRIPTION': 'KETERANGAN',
    'Movement Description': 'Keterangan Mutasi',
    'By signing this document, the parties declare that the asset listed in this document has been handed over and received in accordance with the movement information recorded in the Asset Tracker system.': 'Dengan ditandatanganinya dokumen ini, para pihak menyatakan bahwa asset sebagaimana tercantum dalam dokumen ini telah diserahkan dan diterima sesuai dengan informasi mutasi yang tercatat pada sistem Asset Tracker.',
    'Approval / Handover': 'Persetujuan / Serah Terima',
    'HANDED OVER BY': 'PIHAK YANG MENYERAHKAN',
    'Position': 'Jabatan',
    'Signature of the handing-over party': 'Tanda tangan penyerah',
    'No signature': 'Tidak ada tanda tangan',
    'Signed': 'Ditandatangani',
    'RECEIVED BY': 'PIHAK YANG MENERIMA',
    'Signature of the receiving party': 'Tanda tangan penerima',
    'Asset Movement Document': 'Dokumen Mutasi Asset',
    'Verification': 'Verifikasi',
    'Add a new asset to Asset Tracker': 'Tambahkan asset baru ke dalam Asset Tracker',
    'Main Information': 'Informasi Utama',
    'Example: AST-001': 'Contoh: AST-001',
    'Example: Dell Latitude Laptop': 'Contoh: Laptop Dell Latitude',
    '-- Select Category --': '-- Pilih Category --',
    'Example: Dell': 'Contoh: Dell',
    'Example: Latitude 5440': 'Contoh: Latitude 5440',
    '-- Select Location --': '-- Pilih Location --',
    '-- Select Department --': '-- Pilih Department --',
    '-- Select Vendor --': '-- Pilih Vendor --',
    'PIC Name': 'Nama PIC',
    'Upload Asset Photo': 'Upload Foto Asset',
    'Choose an asset photo from your computer.': 'Pilih foto asset dari komputer Anda.',
    'Allowed formats: JPG, JPEG, PNG, WEBP': 'Format yang diperbolehkan: JPG, JPEG, PNG, WEBP',
    'Asset Photo Preview': 'Preview Foto Asset',
    'Location & Organization': 'Lokasi & Organisasi',
    'Purchase Information': 'Informasi Pembelian',
    'Example: 3 Years': 'Contoh: 3 Tahun',
    'Enter notes or a description for this asset...': 'Masukkan keterangan atau deskripsi asset...',
    'Save Asset': 'Simpan Asset',
    'Photo format must be JPG, JPEG, PNG, or WEBP.': 'Format foto harus JPG, JPEG, PNG, atau WEBP.',
    'Maximum photo size is 5 MB.': 'Ukuran foto maksimal 5 MB.',
    'Format: JPG, JPEG, PNG, WEBP.': 'Format: JPG, JPEG, PNG, WEBP.',
    'Delete photo when saved': 'Hapus foto saat disimpan',
    'Check only if you want to delete the asset photo.': 'Centang hanya jika foto asset ingin dihapus.',
    'Select Category': 'Pilih Category',
    'Select Location': 'Pilih Location',
    'Select Department': 'Pilih Department',
    'Select Vendor': 'Pilih Vendor',
    'Select Status': 'Pilih Status',
    'Enter the asset description...': 'Masukkan deskripsi asset...',
    'Unsupported photo format.': 'Format foto tidak didukung.',
    'Add Asset Movement': 'Tambah Mutasi Asset',
    'Record asset movement and changes in location, department, and PIC.': 'Catat perpindahan asset dan perubahan lokasi, department, serta PIC.',
    'Asset to be moved': 'Asset yang akan dimutasi',
    'Example: Employee rotation': 'Contoh: Rotasi karyawan',
    'Asset Change': 'Perubahan Asset',
    'CURRENT CONDITION': 'KONDISI SAAT INI',
    'NEW CONDITION': 'KONDISI BARU',
    'Destination Location': 'Lokasi Tujuan',
    'Destination Department': 'Department Tujuan',
    'New PIC': 'PIC Baru',
    'New PIC name': 'Nama PIC baru',
    'Current condition': 'Kondisi saat ini',
    'is automatically taken from the asset data. You only need to specify': 'diambil otomatis dari data asset. Anda hanya perlu menentukan',
    'the destination condition': 'kondisi tujuan',
    'Movement Notes': 'Catatan Mutasi',
    'Add notes if needed...': 'Tambahkan catatan jika diperlukan...',
    'Signatory Information': 'Informasi Penandatangan',
    'Handed Over By': 'Pihak yang Menyerahkan',
    'Name': 'Nama',
    'Name of the person handing over': 'Nama penyerah',
    'Position of the person handing over': 'Jabatan penyerah',
    'Signature': 'Tanda Tangan',
    'Signature URL / data': 'URL / data tanda tangan',
    'Received By': 'Pihak yang Menerima',
    'Name of the recipient': 'Nama penerima',
    'Position of the recipient': 'Jabatan penerima',
    'Save Movement': 'Simpan Mutasi',
    'Correct Asset Movement': 'Koreksi Movement Asset',
    'Fix the movement data': 'Perbaiki data movement',
    'without creating a new movement number.': 'tanpa membuat nomor movement baru.',
    'Attention': 'Perhatian',
    'Correction is only allowed for the': 'Koreksi hanya diperbolehkan untuk',
    'most recent movement': 'movement terakhir',
    'of this asset. If the old signature is still correct, you can keep it. If the person handing over or receiving has changed, use the': 'dari asset ini. Jika tanda tangan lama masih benar, Anda dapat mempertahankannya. Jika pihak yang menyerahkan atau menerima berubah, gunakan tombol',
    'Re-sign button': 'tombol Tanda Tangan Ulang',
    'Movement Details': 'Detail Perpindahan',
    'Origin Location': 'Lokasi Asal',
    'The origin location is determined automatically from the movement history and cannot be changed.': 'Lokasi asal ditentukan otomatis dari histori movement dan tidak dapat diubah.',
    'Origin Department': 'Department Asal',
    'The origin department is determined automatically from the movement history and cannot be changed.': 'Department asal ditentukan otomatis dari histori movement dan tidak dapat diubah.',
    'Origin PIC': 'PIC Asal',
    'The origin PIC is determined automatically from the movement history and cannot be changed.': 'PIC asal ditentukan otomatis dari histori movement dan tidak dapat diubah.',
    'Destination PIC': 'PIC Tujuan',
    'Enter the movement reason': 'Masukkan alasan movement',
    'Enter additional notes': 'Masukkan catatan tambahan',
    'Saved signature': 'Tanda tangan yang tersimpan',
    'Signature of the person handing over': 'Tanda tangan penyerah',
    'Use Old Signature': 'Gunakan Tanda Tangan Lama',
    'Sign here using a mouse, touchpad, or touchscreen': 'Tanda tangan di sini menggunakan mouse, touchpad atau layar sentuh',
    'Keep Old': 'Pertahankan Lama',
    'The old signature is being used.': 'Tanda tangan lama digunakan.',
    'No signature yet.': 'Belum ada tanda tangan.',
    'Use a mouse/touchpad to draw. Click Delete to create a new signature.': 'Gunakan mouse/touchpad untuk menggambar. Klik Hapus untuk membuat tanda tangan baru.',
    'Signature of the recipient': 'Tanda tangan penerima',
    'Save Correction': 'Simpan Koreksi',
    'A new signature is being drawn.': 'Tanda tangan baru sedang dibuat.',
    'New signature ready to be saved.': 'Tanda tangan baru siap disimpan.',
    'Signature deleted.': 'Tanda tangan dihapus.',
    'There is no old signature.': 'Tidak ada tanda tangan lama.',
    'The old signature will be kept.': 'Tanda tangan lama akan dipertahankan.',
    'Reset all correction data to the original state?': 'Kembalikan seluruh data koreksi ke kondisi awal?',
    'Print Asset Labels': 'Cetak Label Asset',
    'Print Asset Label': 'Cetak Label Asset',
    'selected for printing.': 'dipilih untuk dicetak.',
    'ASSET IDENTIFICATION': 'IDENTIFIKASI ASSET',
    'Serial': 'Serial',
    'PROPERTY OF COMPANY': 'MILIK PERUSAHAAN',
    'QR': 'QR',
    'Print QR / Label Asset': 'Cetak QR / Label Asset',
    'Format:': 'Format:',
    '— 5 columns × 8 rows — 40 labels / sheet.': '— 5 kolom × 8 baris — 40 label / lembar.',
    'Each asset is printed as': 'Setiap asset dicetak',
    '5 labels': '5 label',
    'for laptop, charger, box, bag, and accessories.': 'untuk laptop, charger, kardus, tas, dan aksesori.',
    'Select Asset': 'Pilih Asset',
    'No assets to print.': 'Tidak ada asset untuk dicetak.',
    'Please select an asset first.': 'Silakan pilih asset terlebih dahulu.',
    'Select Assets for Label Printing': 'Pilih Asset untuk Print Label',
    'Select the assets whose labels you want to print.': 'Pilih asset yang ingin dicetak labelnya.',
    'Asset Tag, name, brand, model, serial...': 'Asset Tag, nama, brand, model, serial...',
    'selected': 'dipilih',
    'Select All': 'Pilih Semua',
    'Clear All': 'Batalkan Semua',
    'No assets.': 'Tidak ada asset.',
    'No matching assets found.': 'Tidak ada asset yang sesuai dengan pencarian.',
    'Select assets then click': 'Pilih asset kemudian klik',
    'Print Label': 'Cetak Label',
    'Please select at least one asset.': 'Pilih minimal satu asset.',
    'Back to Asset': 'Kembali ke Asset',
    'Movement': 'Mutasi',
    'movement': 'mutasi',
    'Current Location': 'Lokasi Saat Ini',
    'Current Department': 'Departemen Saat Ini',
    'Current PIC': 'PIC Saat Ini',
    'Current Asset Condition': 'Kondisi Asset Saat Ini',
    'Movement History': 'Riwayat Movement',
    'FROM': 'DARI',
    'TO': 'KE',
    'CURRENT': 'SAAT INI',
    'HISTORY': 'RIWAYAT',
    'Correct': 'Koreksi',
    'Asset History': 'Riwayat Asset',
    'Asset Journey History': 'Riwayat Perjalanan Asset',
    'Complete history of asset movement based on all movements recorded in the system.': 'Histori lengkap perpindahan asset berdasarkan seluruh movement yang tercatat di sistem.',
    'CURRENT ASSET CONDITION': 'KONDISI ASSET SAAT INI',
    'Movement Timeline': 'Timeline Movement',
    'LATEST CONDITION': 'KONDISI TERAKHIR',
    'Movement #': 'Mutasi #',
    'Print History': 'Print Riwayat',
    'Global Movement': 'Mutasi Global',
    'All asset movement history': 'Seluruh histori movement asset',
    'Filter Movement': 'Filter Movement',
    'Movement No / Asset Tag / Asset Name / PIC': 'Movement No / Asset Tag / Asset Name / PIC',
    'Until': 'Sampai',
    'Current': 'Saat Ini',
    'History': 'Riwayat',
    'Movement Data': 'Data Movement',
    'data': 'data',
    'Movement page navigation': 'Navigasi halaman movement',
    'No movements found': 'Tidak ada movement ditemukan',
    'No data matches the filter.': 'Tidak ada data yang sesuai dengan filter.',
    'Import Asset': 'Impor Asset',
    'Import multiple assets using Excel.': 'Import banyak asset menggunakan Excel.',
    'Upload Excel': 'Upload Excel',
    'Excel File': 'File Excel',
    'Supported format:': 'Format yang didukung:',
    'or': 'atau',
    'Download Excel Template': 'Download Template Excel',
    'Excel Format': 'Format Excel',
    'The first row of the Excel file must contain the following column names:': 'Baris pertama Excel harus berisi nama kolom berikut:',
    'Required': 'Wajib',
    'Optional': 'Opsional',
    'Asset Import Result': 'Hasil Import Asset',
    'Successful': 'Berhasil',
    'assets added successfully': 'asset berhasil ditambahkan',
    'Failed': 'Gagal',
    'rows failed to process': 'baris gagal diproses',
    'Error Details': 'Detail Error',
    'Import Again': 'Import Lagi',
    'View Assets': 'Lihat Asset',
    'User Management': 'Manajemen User',
    'Manage user accounts and access rights': 'Kelola akun dan hak akses pengguna',
    'Add User': 'Tambah User',
    'Role': 'Role',
    'Delete this user?': 'Hapus user ini?',
    'No users yet.': 'Belum ada user.',
    'Edit User': 'Edit User',
    'Save User': 'Simpan User',
    'Active Account': 'Akun Aktif',
    'Menu Management': 'Manajemen Menu',
    'Manage the navigation menu shown in the navbar': 'Atur menu navigasi yang tampil di navbar',
    'Add Menu Item': 'Tambah Menu',
    'Label': 'Label',
    'URL': 'URL',
    'Icon': 'Ikon',
    'Order': 'Urutan',
    'Dropdown': 'Dropdown',
    'All Roles': 'Semua Role',
    'Delete this menu? Its submenus will also be deleted.': 'Hapus menu ini? Submenu di dalamnya juga akan terhapus.',
    'Delete this menu?': 'Hapus menu ini?',
    'No menu items yet.': 'Belum ada menu.',
    'Example: Stock Report': 'Contoh: Laporan Stok',
    'Can be left blank if this menu item will be a divider.': 'Boleh dikosongkan kalau menu ini dijadikan garis pemisah.',
    'Example: /assets or leave blank if this is a dropdown group': 'Contoh: /assets atau kosongkan jika ini grup dropdown',
    'Leave blank if this menu item is only a dropdown group (has submenus).': 'Kosongkan jika menu ini hanya jadi grup dropdown (punya submenu).',
    'Icon (Bootstrap Icons)': 'Ikon (Bootstrap Icons)',
    'Example: bi-box-seam': 'Contoh: bi-box-seam',
    'See the list of icon names at': 'Lihat daftar nama icon di',
    'Parent Menu': 'Induk Menu (Parent)',
    'None (top-level menu)': 'Tidak ada (menu utama)',
    'Select a parent menu if this is a submenu (dropdown).': 'Pilih menu utama jika ini submenu (dropdown).',
    'Smaller numbers appear first.': 'Angka lebih kecil tampil lebih dulu.',
    'Visible For Roles': 'Terlihat Untuk Role',
    'Leave all unchecked if this menu item should be visible to all roles.': 'Kosongkan semua jika menu ini boleh dilihat semua role.',
    'Active Menu': 'Menu Aktif',
    'Make this a divider (not a link)': 'Jadikan garis pemisah (bukan link)',
    'Save Menu': 'Simpan Menu',
    'Edit Menu Item': 'Edit Menu',
    'Clear Cache': 'Hapus Cache',
    'Clear Browser Cache': 'Bersihkan Cache Browser',
    'If the app display feels "stuck" or is not showing the latest changes, try clearing the browser cache for this page.': 'Kalau tampilan aplikasi terasa "nyangkut" atau tidak menampilkan perubahan terbaru, coba bersihkan cache browser untuk halaman ini.',
    'This does not delete any data in the database, only temporary data stored in your browser. If you do not need to, you may ignore this.': 'Ini tidak menghapus data di database, cuma data sementara yang tersimpan di browser Anda. Kalau tidak diperlukan, boleh diabaikan saja.',
    'Clear Cache Now': 'Bersihkan Cache Sekarang',
    'Clearing...': 'Membersihkan...',
    'Cache cleared successfully. Reloading page...': 'Cache berhasil dibersihkan. Memuat ulang halaman...',
    'Failed to clear cache:': 'Gagal membersihkan cache:',
    'Audit Log': 'Log Aktivitas',
    'History of who added/changed/deleted data': 'Riwayat siapa menambah/mengubah/menghapus data',
    'Time': 'Waktu',
    'User': 'Pengguna',
    'Data Type': 'Tipe Data',
    'Data': 'Data',
    'Add': 'Tambah',
    'Update': 'Ubah',
    'No activity recorded yet.': 'Belum ada aktivitas tercatat.',
    'Audit log page navigation': 'Navigasi halaman audit log',
    'Role Management': 'Manajemen Role',
    'Manage roles and page-level permissions (Create/Read/Edit/Delete)': 'Atur role dan hak akses (Create/Read/Edit/Delete) per halaman',
    'Add Role': 'Tambah Role',
    'Import': 'Import',
    'Role Name': 'Nama Role',
    'User Count': 'Jumlah User',
    'Type': 'Tipe',
    'Built-in': 'Bawaan',
    'Custom': 'Custom',
    'Permissions': 'Hak Akses',
    'Permissions:': 'Hak Akses:',
    'Delete this role?': 'Hapus role ini?',
    'No roles yet.': 'Belum ada role.',
    'Import Permissions': 'Import Hak Akses',
    'Import Roles & Permissions': 'Import Role & Hak Akses',
    'Use the': 'Gunakan',
    'file from the Role Management page as a template. Roles whose names already exist will have their permissions updated (except built-in roles, whose names cannot be changed); roles with new names will be created automatically.': 'file dari halaman Manajemen Role sebagai template. Role yang namanya sudah ada akan diperbarui hak aksesnya (kecuali role bawaan namanya tidak diubah); role dengan nama baru akan otomatis dibuat.',
    'Excel File (.xlsx)': 'File Excel (.xlsx)',
    'Download Template (Export Now)': 'Download Template (Export Sekarang)',
    'Edit Role': 'Edit Role',
    'Set Permissions': 'Atur Hak Akses',
    'Example: Warehouse Staff': 'Contoh: Staff Gudang',
    'After the role is created, you will be directed to the page to set its permissions (Create/Read/Edit/Delete per page). New roles have no access by default.': 'Setelah role dibuat, Anda akan diarahkan ke halaman untuk mengatur hak aksesnya (Create/Read/Edit/Delete per halaman). Role baru defaultnya belum punya akses apapun.',
    'Save & Set Permissions': 'Simpan & Atur Hak Akses',
    'The role': 'Role',
    'always has full access to all pages (superuser), regardless of the settings below. This matrix is for display/reference only.': 'selalu punya akses penuh ke semua halaman (superuser), terlepas dari pengaturan di bawah ini. Matrix ini cuma untuk tampilan/referensi.',
    'Permission Matrix per Page': 'Matrix Hak Akses per Halaman',
    'Object': 'Object',
    'all': 'semua',
    'clear': 'kosongkan',
    'Save Permissions': 'Simpan Hak Akses',
    'Restore from Uploaded File': 'Restore dari File Upload',
    'This will': 'Ini akan',
    'OVERWRITE': 'MENIMPA',
    'the entire database and photos currently in use with the contents of the backup file you upload. The current state will automatically be backed up first before being overwritten.': 'seluruh database dan foto yang sedang berjalan sekarang dengan isi file backup yang Anda upload. Kondisi sekarang akan otomatis di-backup dulu sebelum ditimpa.',
    'Backup File (.zip)': 'File Backup (.zip)',
    'to confirm': 'untuk konfirmasi',
    'Overwrite Database Now': 'Timpa Database Sekarang',
    'Backup Database': 'Backup Database',
    'Back up the database and photo files (assets, company logo) into a single .zip file': 'Backup file database dan foto (asset, logo company) jadi satu file .zip',
    'Backup List': 'Daftar Backup',
    'Create New Backup': 'Buat Backup Baru',
    'File Name': 'Nama File',
    'Size': 'Ukuran',
    'Download': 'Download',
    'Restore': 'Restore',
    'Delete this backup file?': 'Hapus file backup ini?',
    'Restore Database': 'Restore Database',
    'all data currently in use with the contents of backup': 'seluruh data yang sedang berjalan sekarang dengan isi backup',
    'All changes made after that date will be lost.': 'Semua perubahan setelah tanggal itu akan hilang.',
    'The current state will automatically be backed up first before being overwritten, so it can still be restored if you choose incorrectly.': 'Kondisi sekarang akan otomatis di-backup dulu sebelum ditimpa, jadi masih bisa dikembalikan kalau salah pilih.',
    'to confirm:': 'untuk konfirmasi:',
    'Yes, Overwrite Database Now': 'Ya, Timpa Database Sekarang',
    'No backups yet. Click "Create New Backup" above.': 'Belum ada backup. Klik "Buat Backup Baru" di atas.',
    'Backups are stored in the': 'Backup tersimpan di folder',
    'folder on the server. It is recommended to periodically download and store copies elsewhere (Google Drive, USB drive, etc).': 'di server. Sebaiknya download dan simpan salinannya di tempat lain (Google Drive, flashdisk, dsb) secara berkala.',
    'Company Data': 'Data Perusahaan',
    'Company information used on document headers and asset movement receipts': 'Informasi perusahaan yang digunakan pada kop dokumen dan bukti mutasi asset',
    'Edit Company Data': 'Edit Data Perusahaan',
    'Prefix:': 'Prefix:',
    'This data is automatically used in the': 'Data ini otomatis dipakai di kop',
    'Asset Movement Receipt': 'Bukti Mutasi Asset',
    'header and document numbering.': 'dan penomoran dokumen.',
    'Contact Information': 'Informasi Kontak',
    'Website': 'Website',
    'NPWP': 'NPWP',
    'Company data is not yet available.': 'Data perusahaan belum tersedia.',
    'Add company data': 'Tambahkan data perusahaan',
    'Set the company identity used in documents and reports': 'Atur identitas perusahaan yang digunakan pada dokumen dan laporan',
    'Company Information': 'Informasi Perusahaan',
    'Company Name': 'Nama Perusahaan',
    'PT Company Name': 'PT Nama Perusahaan',
    'Full company address': 'Alamat lengkap perusahaan',
    'NPWP Number': 'Nomor NPWP',
    'Document Number Prefix': 'Prefix Nomor Dokumen',
    'Example:': 'Contoh:',
    'produces a number like': 'menghasilkan nomor seperti',
    'Company Logo': 'Logo Perusahaan',
    'No logo yet': 'Belum ada logo',
    'Logo Preview': 'Preview Logo',
    'Upload Logo': 'Upload Logo',
}

# Label menu dinamis (tersimpan di database sebagai MenuItem.label,
# jadi tidak ter-extract otomatis oleh pybabel karena bukan string
# literal). msgid = label ASLI yang tersimpan sekarang (Indonesia),
# msgstr_en = terjemahan Inggris, msgstr_id = sama seperti aslinya.
MENU_LABELS = {
    "Laporan Mutasi": "Movement Report",
    "Master Data": "Master Data",
    "Kategori": "Categories",
    "Lokasi": "Locations",
    "Departemen": "Departments",
    "Hapus Cache": "Clear Cache",
    "Role Akses": "Access Roles",
    "Pengaturan Aplikasi": "Application Settings",
    "Pemisah": "Divider",
}


def build_catalog(pot_path, extra_msgids):
    catalog = polib.pofile(pot_path)
    catalog.metadata_is_fuzzy = False
    existing = {entry.msgid for entry in catalog}
    for msgid in extra_msgids:
        if msgid not in existing:
            catalog.append(polib.POEntry(msgid=msgid, msgstr=""))
    return catalog


def write_en(pot_path, out_path):
    catalog = build_catalog(pot_path, MENU_LABELS.keys())
    catalog.metadata["Language"] = "en"
    for entry in catalog:
        # Sumber string memang bahasa Inggris -> identity translation,
        # KECUALI label menu (yang msgid-nya masih bahasa Indonesia).
        if entry.msgid in MENU_LABELS:
            entry.msgstr = MENU_LABELS[entry.msgid]
        else:
            entry.msgstr = entry.msgid
    catalog.save(out_path)


def write_id(pot_path, out_path):
    catalog = build_catalog(pot_path, MENU_LABELS.keys())
    catalog.metadata["Language"] = "id"
    missing = []
    for entry in catalog:
        if entry.msgid in MENU_LABELS:
            # Label menu sudah dalam bahasa Indonesia -> identity.
            entry.msgstr = entry.msgid
        elif entry.msgid in ID_TRANSLATIONS:
            entry.msgstr = ID_TRANSLATIONS[entry.msgid]
        else:
            missing.append(entry.msgid)
            entry.msgstr = entry.msgid
    catalog.save(out_path)
    return missing


if __name__ == "__main__":
    write_en(POT_PATH, EN_PO_PATH)
    missing = write_id(POT_PATH, ID_PO_PATH)

    print(f"EN catalog written: {EN_PO_PATH}")
    print(f"ID catalog written: {ID_PO_PATH}")

    if missing:
        print(f"\nWARNING: {len(missing)} msgid belum ada terjemahan ID (pakai fallback = msgid asli):")
        for m in missing:
            print(" -", repr(m))
    else:
        print("\nSemua msgid punya terjemahan ID.")
