"""add digital signatures to asset movement

Revision ID: 34bd0574c614
Revises: f864829542ba
Create Date: 2026-08-08 19:04:51.991069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bd0574c614'
down_revision = 'f864829542ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('to_signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_column('to_signature')
        batch_op.drop_column('from_signature')

    # ### end Alembic commands ###
