"""create asset movement corrections

Revision ID: 597f97190103
Revises: 67f437a72058
Create Date: 2026-08-18 17:32:01.487982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597f97190103'
down_revision = '67f437a72058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_movement_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.Column('old_movement_date', sa.Date(), nullable=True),
    sa.Column('old_from_location', sa.String(length=100), nullable=True),
    sa.Column('old_to_location', sa.String(length=100), nullable=True),
    sa.Column('old_from_department', sa.String(length=100), nullable=True),
    sa.Column('old_to_department', sa.String(length=100), nullable=True),
    sa.Column('old_from_pic', sa.String(length=100), nullable=True),
    sa.Column('old_to_pic', sa.String(length=100), nullable=True),
    sa.Column('old_reason', sa.String(length=255), nullable=True),
    sa.Column('old_notes', sa.Text(), nullable=True),
    sa.Column('new_movement_date', sa.Date(), nullable=True),
    sa.Column('new_from_location', sa.String(length=100), nullable=True),
    sa.Column('new_to_location', sa.String(length=100), nullable=True),
    sa.Column('new_from_department', sa.String(length=100), nullable=True),
    sa.Column('new_to_department', sa.String(length=100), nullable=True),
    sa.Column('new_from_pic', sa.String(length=100), nullable=True),
    sa.Column('new_to_pic', sa.String(length=100), nullable=True),
    sa.Column('new_reason', sa.String(length=255), nullable=True),
    sa.Column('new_notes', sa.Text(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['asset_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_movement_corrections')
    # ### end Alembic commands ###
