"""add warranty history

Revision ID: 67f437a72058
Revises: d5d46cc6b27c
Create Date: 2026-08-09 16:30:38.210692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f437a72058'
down_revision = 'd5d46cc6b27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warranty_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('old_warranty', sa.String(length=100), nullable=True),
    sa.Column('old_end_date', sa.Date(), nullable=True),
    sa.Column('new_warranty', sa.String(length=100), nullable=True),
    sa.Column('new_end_date', sa.Date(), nullable=True),
    sa.Column('changed_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warranty_histories')
    # ### end Alembic commands ###
