"""Add vendor and warranty

Revision ID: bdab5cc52ac6
Revises: 05eb43a2dae4
Create Date: 2026-08-08 10:41:47.699413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdab5cc52ac6'
down_revision = '05eb43a2dae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('warranty')
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
