"""add asset photo

Revision ID: d5d46cc6b27c
Revises: fb4c2a4bb368
Create Date: 2026-08-09 10:39:39.161813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d46cc6b27c'
down_revision = 'fb4c2a4bb368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
