"""add asset_photos table

Revision ID: e3a9c4f7b2d1
Revises: 1abfb7d36a86
Create Date: 2026-09-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a9c4f7b2d1'
down_revision = '1abfb7d36a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_photos_asset_id'), ['asset_id'])
    # ### end Alembic commands ###

    # Bawa foto yang sudah ada di kolom assets.photo jadi
    # cover photo pertama di tabel baru, supaya tidak hilang.
    op.get_bind().execute(sa.text(
        "INSERT INTO asset_photos (asset_id, filename, is_cover, sort_order, created_at) "
        "SELECT id, photo, 1, 0, CURRENT_TIMESTAMP FROM assets WHERE photo IS NOT NULL"
    ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_photos_asset_id'))

    op.drop_table('asset_photos')
    # ### end Alembic commands ###
