"""add brand_display_mode to app_settings

Revision ID: e91d3df19b25
Revises: 25a48f2cc2da
Create Date: 2026-09-02 13:42:12.010473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91d3df19b25'
down_revision = '25a48f2cc2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_display_mode', sa.String(length=20), server_default='logo_only', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('brand_display_mode')

    # ### end Alembic commands ###
