"""add app settings table

Revision ID: ee2350a27384
Revises: 19a3f43205f6
Create Date: 2026-09-01 13:26:30.267491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2350a27384'
down_revision = '19a3f43205f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('login_message', sa.String(length=255), nullable=True),
    sa.Column('logo_wide', sa.String(length=255), nullable=True),
    sa.Column('logo_square', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
