"""add movement signer information

Revision ID: f864829542ba
Revises: 70e58834de65
Create Date: 2026-08-08 18:53:02.228059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f864829542ba'
down_revision = '70e58834de65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_signer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('from_signer_position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('to_signer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('to_signer_position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_column('to_signer_position')
        batch_op.drop_column('to_signer_name')
        batch_op.drop_column('from_signer_position')
        batch_op.drop_column('from_signer_name')

    # ### end Alembic commands ###
